"""
Phase 12 â€” Adaptive Trust-Aware Medical RAG Orchestrator.

Wires all previous phases into the complete end-to-end pipeline:

  Step 1  Input Sanitization & Prompt Injection Defense
  Step 2  Drug Entity Normalization (RxCUI resolution)
  Step 3  Query Risk Classification (R0â€“R3)
  Step 4  Hybrid Retrieval (BM25 + Vector + Graph + RRF)
  Step 5  Adaptive Trust Scoring per retrieved chunk
  Step 6  [PRE-GEN] Evidence Eligibility Gate
            FAIL -> Structured Abstention (no LLM call)
  Step 7  Grounded LLM Generation (pluggable backend)
  Step 8  [POST-GEN] Answer Safety Gate (claim verification)
            ABSTAIN -> Structured Abstention
            QUALIFY  -> Qualified answer released
            RELEASE  -> Full answer released
  Step 9  Audit Logging (structured, PHI-free)

All components are injected via protocol interfaces so the
orchestrator is fully unit-testable without live services.

Non-clinical disclaimer:
  Every response includes a mandatory research-output disclaimer.
  This system is NOT an FDA-approved clinical decision tool.
"""

from __future__ import annotations

import hashlib
import re
import uuid
from dataclasses import dataclass, field
from adaptive_trust_medical_rag.security.security_context import SecurityDecision, SecurityState, SecurityContext
from adaptive_trust_medical_rag.security_extensions.injection_detector import PromptInjectionDetector
from adaptive_trust_medical_rag.security_extensions.poisoning_detector import RetrievalPoisoningDetector
from adaptive_trust_medical_rag.security_extensions.boundary_enforcer import AuthorizationBoundary, EntityDomain, ActionType
from adaptive_trust_medical_rag.security.agent_action import parse_action_request, ActionParseError, AgentActionRequest
from adaptive_trust_medical_rag.security.tool_executor import ToolExecutor
from datetime import UTC, datetime
from enum import Enum
from typing import Protocol, runtime_checkable

from adaptive_trust_medical_rag.ingestion.evidence_ingestion import (
    inspect_for_poisoning,
)
from adaptive_trust_medical_rag.retrieval.hybrid_retrieval import (
    Candidate,
    DrugRelationship,
    EmbeddingModel,
    HybridRetrievalEngine,
    ScoredCandidate,
)
from adaptive_trust_medical_rag.security.sanitizer import sanitize_query
from adaptive_trust_medical_rag.trust_scoring.trust_scorer import (
    AdaptiveTrustScorer,
    TrustFactorScores,
    classify_query_risk,
)
from adaptive_trust_medical_rag.verification.claim_verifier import (
    AnswerSafetyGate,
    EvidenceChunk,
    GateDecision,
    VerificationReport,
)
from adaptive_trust_medical_rag.verification.canonical_identity import (
    CanonicalRelationshipIdentity,
    CanonicalDirection,
    normalize_predicate,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: Mandatory disclaimer prepended to every released answer (medical safety rule)
RESEARCH_DISCLAIMER = (
    "\n\n---\n"
    "âš  **Research Output Only** â€” This response is generated by an experimental "
    "research system and is NOT clinical advice, a diagnosis, or a treatment "
    "recommendation. It has not been reviewed or approved by a licensed clinician "
    "or regulatory authority (FDA/EMA). Always consult a qualified healthcare "
    "professional before making any medical decision."
)

#: Structured abstention template (controlled abstention gate â€” medical safety rule)
ABSTENTION_TEMPLATE = (
    "**[SYSTEM ABSTENTION â€” INSUFFICIENT EVIDENCE]**\n\n"
    "This query cannot be answered with the required confidence level "
    "for risk tier {risk_tier} (threshold: {threshold:.0%}).\n\n"
    "**Reason:** {reason}\n\n"
    "Please consult authoritative clinical resources (e.g., FDA label, "
    "clinical pharmacist) for this query." + RESEARCH_DISCLAIMER
)


# ---------------------------------------------------------------------------
# Protocol interfaces (dependency injection)
# ---------------------------------------------------------------------------


@runtime_checkable
class LLMBackend(Protocol):
    """
    Protocol for pluggable LLM generation backends.
    Compatible with Google GenAI, OpenAI, and local models.
    """

    def generate(self, prompt: str) -> str:
        """Generate a response for the given grounded prompt."""
        ...


@runtime_checkable
class DrugNormalizerProtocol(Protocol):
    """Protocol for drug entity normalization backends."""

    def normalize(self, query: str) -> list[str]:
        """Return a list of normalized drug names found in the query."""
        ...


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------


class PipelineStatus(str, Enum):
    released = "released"
    qualified = "qualified"
    abstained = "abstained"
    error = "error"


@dataclass
class RAGRequest:
    """Incoming query to the RAG pipeline."""

    query: str
    session_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    risk_tier_override: str | None = None  # override auto-classification if needed
    top_k: int = 10


@dataclass
class RAGResponse:
    """Final structured response from the RAG pipeline."""

    session_id: str
    query_hash: str  # SHA-256 of sanitized query (audit log â€” no raw PII)
    risk_tier: str
    status: PipelineStatus
    answer: str
    confidence: float
    trust_scores: list[float]
    retrieved_chunk_ids: list[str]
    gate_decision: str
    verification_report: VerificationReport | None
    audit_log: dict
    security_events: list[SecurityDecision] = field(default_factory=list)
    generated_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    @property
    def is_released(self) -> bool:
        return self.status in (PipelineStatus.released, PipelineStatus.qualified)


from dataclasses import field
@dataclass

class EvidenceEligibilityResult:
    """Result of the pre-generation evidence eligibility gate."""

    passed: bool
    eligible_chunks: list[ScoredCandidate]
    rejected_chunk_ids: list[str]
    reason: str | None = None
    rejection_reasons: dict[str, str] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Grounded prompt builder
# ---------------------------------------------------------------------------

_PROMPT_TEMPLATE = """\
You are a medical evidence synthesis assistant. Your task is to answer the \
clinical pharmacology query below using ONLY the retrieved evidence provided. \
Do NOT generate information not present in the evidence. \
Cite each factual claim with [Source N] where N is the evidence index.

QUERY: {query}

RISK TIER: {risk_tier} â€” {risk_description}

RETRIEVED EVIDENCE:
{evidence_block}

INSTRUCTIONS:
- Answer in clear, precise clinical language.
- Every factual claim MUST be cited with [Source N].
- If the evidence is insufficient to answer, state that clearly.
- Do NOT speculate beyond the retrieved evidence.
- Do NOT fabricate citations, PMIDs, or dosing data.
"""

_RISK_DESCRIPTIONS = {
    "R0": "Informational / General pharmacology",
    "R1": "Standard clinical guidance",
    "R2": "High caution â€” vulnerable populations / black-box warnings",
    "R3": "Critical safety / contraindications / narrow therapeutic index",
}


def build_grounded_prompt(
    query: str,
    risk_tier: str,
    candidates: list[ScoredCandidate],
) -> str:
    """Build a structured, grounded prompt from retrieved evidence candidates."""
    evidence_lines: list[str] = []
    for i, sc in enumerate(candidates, start=1):
        auth = sc.candidate.source_authority
        evidence_lines.append(
            f"[Source {i}] (authority={auth:.2f}, chunk={sc.candidate.chunk_id})\n"
            f"{sc.candidate.text.strip()}"
        )
    evidence_block = "\n\n".join(evidence_lines) if evidence_lines else "(No evidence retrieved)"
    return _PROMPT_TEMPLATE.format(
        query=query,
        risk_tier=risk_tier,
        risk_description=_RISK_DESCRIPTIONS.get(risk_tier, "Unknown"),
        evidence_block=evidence_block,
    )


# ---------------------------------------------------------------------------
# Evidence Eligibility Gate (Pre-generation)
# ---------------------------------------------------------------------------


class EvidenceEligibilityGate:
    """
    Pre-generation gate: evaluates retrieved chunks before LLM context is built.

    Rejects chunks that:
    - Have poisoning_score > 0.4
    - Have trust_score below the risk-tier threshold
    - Have source_authority below minimum viable authority (0.3)

    If too few eligible chunks remain, triggers abstention.
    """

    MIN_AUTHORITY: float = 0.3
    MIN_ELIGIBLE_CHUNKS: int = 1

    #: Trust score thresholds per risk tier (mirrors medical-safety rules)
    TIER_THRESHOLDS: dict[str, float] = {
        "R0": 0.30,
        "R1": 0.45,
        "R2": 0.60,
        "R3": 0.75,
    }

    def evaluate(
        self,
        candidates: list[ScoredCandidate],
        risk_tier: str,
        trust_scores: dict[str, float],
        retrieval_security_states: dict[str, SecurityDecision] | None = None,
        grounding_states: dict = None,
        integrity_states: dict = None,
        candidate_injection_states: dict = None,
    ) -> EvidenceEligibilityResult:
        threshold = self.TIER_THRESHOLDS.get(risk_tier, 0.45)
        eligible: list[ScoredCandidate] = []
        rejected_ids: list[str] = []
        reasons: dict[str, str] = {}

        for sc in candidates:
            cand = sc.candidate
            trust = trust_scores.get(cand.chunk_id, 0.0)

            if retrieval_security_states and cand.chunk_id in retrieval_security_states:
                sec_state = retrieval_security_states[cand.chunk_id].decision
                if sec_state == SecurityState.BLOCK:
                    rejected_ids.append(cand.chunk_id)
                    reasons[cand.chunk_id] = retrieval_security_states[cand.chunk_id].reason_code
                    continue
                    
            if integrity_states and cand.chunk_id in integrity_states:
                if integrity_states[cand.chunk_id].status.name == 'MISMATCH':
                    rejected_ids.append(cand.chunk_id)
                    reasons[cand.chunk_id] = 'INTEGRITY_MISMATCH'
                    continue
                elif integrity_states[cand.chunk_id].status.name == 'MISSING':
                    rejected_ids.append(cand.chunk_id)
                    reasons[cand.chunk_id] = 'INTEGRITY_MISSING_REFERENCE'
                    continue

            if grounding_states and cand.chunk_id in grounding_states:
                g_status = grounding_states[cand.chunk_id].status.name
                if g_status in ('UNSUPPORTED', 'CONTRADICTED', 'NO_RELEVANT_RELATION', 'ENTITY_PAIR_MISMATCH', 'UNVERIFIABLE'):
                    rejected_ids.append(cand.chunk_id)
                    reasons[cand.chunk_id] = 'RELATIONSHIP_GROUNDING_UNSUPPORTED'
                    continue
                elif g_status == 'AMBIGUOUS':
                    # Project policy: fail-closed for ambiguous relationships
                    rejected_ids.append(cand.chunk_id)
                    reasons[cand.chunk_id] = 'RELATIONSHIP_GROUNDING_AMBIGUOUS'
                    continue

            if candidate_injection_states and cand.chunk_id in candidate_injection_states:
                sec_state = candidate_injection_states[cand.chunk_id].decision
                if sec_state in (SecurityState.BLOCK, SecurityState.FLAG):
                    rejected_ids.append(cand.chunk_id)
                    reasons[cand.chunk_id] = 'PROMPT_INJECTION_DETECTED'
                    continue

            if cand.poisoning_score > 0.4:
                rejected_ids.append(cand.chunk_id)
                reasons[cand.chunk_id] = 'HIGH_POISONING_SCORE'
                continue

            if trust < threshold:
                rejected_ids.append(cand.chunk_id)
                reasons[cand.chunk_id] = 'INSUFFICIENT_TRUST'
                continue

            if cand.source_authority < self.MIN_AUTHORITY:
                rejected_ids.append(cand.chunk_id)
                reasons[cand.chunk_id] = 'LOW_AUTHORITY'
                continue

            eligible.append(sc)

        if len(eligible) < self.MIN_ELIGIBLE_CHUNKS:
            return EvidenceEligibilityResult(
                passed=False,
                eligible_chunks=[],
                rejected_chunk_ids=rejected_ids,
                reason=f'Insufficient eligible evidence: {len(eligible)} chunk(s) passed all gates. {len(rejected_ids)} chunk(s) rejected.',
                rejection_reasons=reasons,
            )

        return EvidenceEligibilityResult(
            passed=True,
            eligible_chunks=eligible,
            rejected_chunk_ids=rejected_ids,
            rejection_reasons=reasons,
        )
# ---------------------------------------------------------------------------
# RAG Orchestrator
# ---------------------------------------------------------------------------


class AdaptiveTrustRAGOrchestrator:
    """
    End-to-end Adaptive Trust-Aware Medical RAG Orchestrator.

    Wires together all 12 pipeline phases. All backends are injected
    via protocol interfaces for testability.

    Usage:
        orchestrator = AdaptiveTrustRAGOrchestrator(
            corpus=chunks,
            embedding_model=my_embedder,
            llm_backend=my_llm,
            drug_normalizer=my_normalizer,
        )
        response = orchestrator.query(RAGRequest(query="warfarin aspirin interaction"))
    """

    def __init__(
        self,
        corpus: list[Candidate],
        embedding_model: EmbeddingModel,
        llm_backend: LLMBackend,
        drug_normalizer: DrugNormalizerProtocol | None = None,
        drug_relationships: list[DrugRelationship] | None = None,
        grounding_validator = None,
        integrity_validator = None,
        retrieval_engine = None,
        **kwargs,
    ) -> None:
        self._trust_scorer = AdaptiveTrustScorer()
        self._prompt_detector = PromptInjectionDetector()
        self._poisoning_detector = RetrievalPoisoningDetector()
        self._auth_boundary = AuthorizationBoundary()
        self._tool_executor = ToolExecutor()
        self._eligibility_gate = EvidenceEligibilityGate()
        self._grounding_validator = grounding_validator
        self._integrity_validator = integrity_validator

        # Retrieval engine - pluggable or fallback
        if retrieval_engine is not None:
            self._retrieval = retrieval_engine
        else:
            self._retrieval = HybridRetrievalEngine(corpus, embedding_model)
            for rel in drug_relationships or []:
                self._retrieval.graph.add_relationship(rel)

        self._llm = llm_backend
        self._drug_normalizer = drug_normalizer

    # â”€â”€ Public API â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    def query(self, request: RAGRequest) -> RAGResponse:
        """
        Execute the end-to-end Adaptive Trust-Aware RAG pipeline.
        """
        import uuid
        session_id = request.session_id or f"sess_{uuid.uuid4().hex[:8]}"
        request_id = f"req_{uuid.uuid4().hex[:8]}"
        
        security_context = SecurityContext(
            request_id=request_id,
            session_id=session_id,
            principal="USER"
        )
        
        audit: list[dict[str, Any]] = []

        def _log(step: str, detail: dict) -> None:
            audit.append({"step": step, "detail": detail})

        _log("session_start", {"session_id": session_id})

        # Phase 14: Step 1.5 - Prompt Injection Detection (BEFORE processing)
        # Using simple query, not yet sanitized, for injection detection
        injection_decision = self._prompt_detector.inspect(request.query, request_id)
        security_context.injection_status = injection_decision
        security_context.add_decision(injection_decision)
        _log("prompt_injection_detection", {"decision": injection_decision.decision.value, "reason": injection_decision.reason_code})
        
        if injection_decision.decision == SecurityState.BLOCK:
            return self._abstain(
                session_id=session_id,
                query_hash=hashlib.sha256(request.query.encode()).hexdigest(),
                risk_tier="R3",  # default high risk for malicious requests
                reason="Query blocked due to security policy (Prompt Injection).",
                audit=audit,
                security_context=security_context
            )

        # ðŸš€ Step 1: Input sanitization
        sanitization_result = sanitize_query(request.query)
        sanitized_query = sanitization_result.sanitized

        query_hash = hashlib.sha256(sanitized_query.encode()).hexdigest()
        _log("sanitization", {"query_hash": query_hash})

        if sanitization_result.rejected:
            # Re-evaluate with injection detector explicitly logging block
            return self._abstain(
                session_id=session_id,
                query_hash=query_hash,
                risk_tier="R0",
                reason="Query rejected by security sanitizer.",
                audit=audit,
                security_context=security_context
            )

        # ðŸš€ Step 2: Drug entity normalization
        if self._drug_normalizer:
            query_drugs = self._drug_normalizer.normalize(sanitized_query)
        else:
            query_drugs = self._extract_drugs_simple(sanitized_query)
        _log("entity_normalization", {"drugs": query_drugs})

        # Step 2.5: Build canonical drug RxCUI map
        drug_rxcui_map: dict[str, str] = {}
        if hasattr(self._drug_normalizer, '_cache'):
            cache = getattr(self._drug_normalizer, '_cache')
            for drug_name in query_drugs:
                cached = cache.lookup(drug_name)
                if cached and cached.get('rxcui'):
                    drug_rxcui_map[drug_name.lower()] = cached['rxcui']

        # ðŸš€ Step 3: Query risk classification
        if request.risk_tier_override:
            risk_tier = request.risk_tier_override
        else:
            risk_tier = classify_query_risk(sanitized_query)

        _log("risk_classification", {"risk_tier": risk_tier})

        # ðŸš€ Step 4: Hybrid retrieval
        candidates = self._retrieval.retrieve(
            query=sanitized_query,
            query_drugs=query_drugs,
            top_k=request.top_k,
        )

        _log(
            "retrieval",
            {
                "candidate_count": len(candidates),
                "chunk_ids": [sc.candidate.chunk_id for sc in candidates],
            },
        )
        
        # Phase 14: Step 4.5 - Retrieval Poisoning Detection
        retrieval_security_states = {}
        for sc in candidates:
            cand = sc.candidate
            poison_dec = self._poisoning_detector.inspect_provenance(cand.metadata.get("provenance", {}), cand.chunk_id, request_id)
            retrieval_security_states[cand.chunk_id] = poison_dec
            security_context.add_decision(poison_dec)
        security_context.retrieval_security_states = retrieval_security_states

        # ðŸš€ Step 5: Adaptive trust scoring
        trust_scores: dict[str, float] = {}
        missing_factors_dict: dict[str, list[str]] = {}
        for sc in candidates:
            cand = sc.candidate
            entity_match = 1.0 if any(d in cand.text.lower() for d in query_drugs) else 0.5
            factors = TrustFactorScores(
                source_authority=cand.source_authority,
                entity_match=entity_match,
                freshness=float(cand.metadata.get("freshness_score", 0.8)),
                consistency=1.0 - cand.poisoning_score,
                anti_poisoning=1.0 - cand.poisoning_score,
                anti_injection=1.0,  # FIXED: Default clean; injection is evaluated as a hard gate later
            )
            result = self._trust_scorer.score(
                chunk_id=cand.chunk_id,
                risk_class=risk_tier,
                factors=factors,
            )
            trust_scores[cand.chunk_id] = result.trust_score
            missing_factors_dict[cand.chunk_id] = result.missing_factors

        _log(
            "trust_scoring",
            {
                "scores": {cid: round(s, 4) for cid, s in trust_scores.items()},
            },
        )

        # Step 6: Evidence eligibility gate (pre-generation)
        grounding_states = {}
        integrity_states = {}
        candidate_injection_states = {}
        for sc in candidates:
            cand = sc.candidate
            if getattr(self, "_grounding_validator", None):
                # Backwards compatible: if validate accepts query, pass it
                import inspect
                sig = inspect.signature(self._grounding_validator.validate)
                if "query" in sig.parameters:
                    grounding_states[cand.chunk_id] = self._grounding_validator.validate(cand, query=request.query)
                else:
                    grounding_states[cand.chunk_id] = self._grounding_validator.validate(cand)
            if getattr(self, "_integrity_validator", None):
                integrity_states[cand.chunk_id] = self._integrity_validator.validate(cand)
            inj_dec = self._prompt_detector.inspect(cand.text, request_id)
            candidate_injection_states[cand.chunk_id] = inj_dec
            security_context.add_decision(inj_dec)

        eligibility = self._eligibility_gate.evaluate(candidates, risk_tier, trust_scores, retrieval_security_states, grounding_states, integrity_states, candidate_injection_states)

        _log(
            "evidence_eligibility_gate",
            {
                "passed": eligibility.passed,
                "eligible_count": len(eligibility.eligible_chunks),
                "rejected_ids": eligibility.rejected_chunk_ids,
                "reason": eligibility.reason,
                "rejection_reasons": eligibility.rejection_reasons,
            },
        )

        if not eligibility.passed:
            return self._abstain(
                session_id=session_id,
                query_hash=query_hash,
                risk_tier=risk_tier,
                reason=eligibility.reason or "Evidence eligibility gate failed.",
                audit=audit,
                security_context=security_context
            )

        eligible_candidates = eligibility.eligible_chunks



        # ðŸš€ Step 7: Grounded LLM generation
        prompt = build_grounded_prompt(sanitized_query, risk_tier, eligible_candidates)
        raw_answer = self._llm.generate(prompt)

        _log("llm_generation", {"prompt_length": len(prompt), "answer_length": len(raw_answer)})

        # ðŸš€ Step 7.5: Classify Output (Claim vs Action)
        # FAIL-CLOSED: malformed/unknown actions -> controlled abstention, never fallback
        try:
            action_request = parse_action_request(
                llm_output=raw_answer,
                principal=security_context.principal,
                request_id=request_id,
            )
        except ActionParseError as e:
            _log("action_parse_error", {"error": str(e)})
            return self._abstain(
                session_id=session_id,
                query_hash=query_hash,
                risk_tier=risk_tier,
                reason=f"Invalid action request in LLM output: {e}",
                audit=audit,
                security_context=security_context
            )
        
        if action_request is not None:
            _log("action_request_parsed", {
                "action_type": action_request.action_type.value,
                "domain": action_request.entity_domain.value,
                "principal": action_request.principal,
            })
            
            auth_decision = self._auth_boundary.authorize(
                domain=action_request.entity_domain,
                action=action_request.action_type,
                request_id=request_id,
                principal=action_request.principal
            )
            security_context.authorization_states.append(auth_decision)
            security_context.add_decision(auth_decision)
            _log("authorization_decision", {
                "decision": auth_decision.decision.value,
                "reason": auth_decision.reason_code,
            })
            
            if auth_decision.decision == SecurityState.UNAUTHORIZED_ACTION_REJECTED:
                return self._abstain(
                    session_id=session_id,
                    query_hash=query_hash,
                    risk_tier=risk_tier,
                    reason=f"Authorization Boundary Blocked Action: {action_request.action_type.value} on {action_request.entity_domain.value}.",
                    audit=audit,
                    security_context=security_context
                )
            
            # Authorized â€” execute via controlled executor
            exec_record = self._tool_executor.execute(action_request)
            _log("tool_execution", {
                "action_type": exec_record.action_type,
                "domain": exec_record.entity_domain,
                "success": exec_record.success,
            })
            return RAGResponse(
                session_id=session_id,
                query_hash=query_hash,
                risk_tier=risk_tier,
                status=PipelineStatus.released,
                answer=f"Tool {exec_record.action_type} executed on {exec_record.entity_domain}.",
                confidence=1.0,
                trust_scores=list(trust_scores.values()),
                retrieved_chunk_ids=[sc.candidate.chunk_id for sc in eligible_candidates],
                gate_decision="tool_executed",
                verification_report=None,
                audit_log=audit,
                security_events=security_context.cumulative_decisions
            )

        # ðŸš€ Step 8: Answer safety gate (post-generation)
        # Build source canonical identities
        source_identity = None
        if len(drug_rxcui_map) >= 2:
            rxcui_list = list(drug_rxcui_map.items())
            subject_name, subject_rxcui = rxcui_list[0]
            object_name, object_rxcui = rxcui_list[1]
            predicate = "INTERACTION"
            source_identity = CanonicalRelationshipIdentity(
                subject_rxcui=subject_rxcui,
                object_rxcui=object_rxcui,
                predicate=predicate,
                direction=CanonicalDirection.A_TO_B,
            )

        evidence_chunks = []
        for i, sc in enumerate(eligible_candidates, start=1):
            identity_copy = None
            if source_identity is not None:
                identity_copy = CanonicalRelationshipIdentity(
                    subject_rxcui=source_identity.subject_rxcui,
                    object_rxcui=source_identity.object_rxcui,
                    predicate=source_identity.predicate,
                    direction=source_identity.direction,
                    provenance_chunk_id=sc.candidate.chunk_id
                )
            evidence_chunks.append(
                EvidenceChunk(
                    chunk_id=sc.candidate.chunk_id,
                    text=sc.candidate.text,
                    source_authority=sc.candidate.source_authority,
                    citation_index=i,
                    trust_score=trust_scores.get(sc.candidate.chunk_id, 0.0),
                    missing_factors=missing_factors_dict.get(sc.candidate.chunk_id, []),
                    relationship_scope=grounding_states[sc.candidate.chunk_id].status.name if (grounding_states and sc.candidate.chunk_id in grounding_states) else None,
                    relationship_identity=identity_copy
                )
            )

        safety_gate = AnswerSafetyGate(risk_tier=risk_tier)
        verification = safety_gate.verify(raw_answer, evidence_chunks)

        _log(
            "answer_safety_gate",
            {
                "decision": verification.decision.value,
                "confidence": verification.confidence,
                "grounding_ratio": verification.grounding_ratio,
                "contradiction_score": verification.contradiction_score,
                "explanation": verification.explanation,
            },
        )

        # ðŸš€ Step 9: Final answer formatting

        if verification.decision == GateDecision.abstain:
            return self._abstain(
                session_id=session_id,
                query_hash=query_hash,
                risk_tier=risk_tier,
                reason=verification.explanation,
                audit=audit,
                verification=verification,
                trust_scores=list(trust_scores.values()),
                chunk_ids=[sc.candidate.chunk_id for sc in eligible_candidates],
                security_context=security_context
            )

        final_answer = (
            verification.qualified_answer
            if verification.decision == GateDecision.qualify and verification.qualified_answer
            else raw_answer
        ) + RESEARCH_DISCLAIMER

        status = (
            PipelineStatus.qualified
            if verification.decision == GateDecision.qualify
            else PipelineStatus.released
        )

        return RAGResponse(
            session_id=session_id,
            query_hash=query_hash,
            risk_tier=risk_tier,
            status=status,
            answer=final_answer,
            confidence=verification.confidence,
            trust_scores=list(trust_scores.values()),
            retrieved_chunk_ids=[sc.candidate.chunk_id for sc in eligible_candidates],
            gate_decision=verification.decision.value,
            verification_report=verification,
            audit_log=audit,
            security_events=security_context.cumulative_decisions
        )



    # â”€â”€ Internal helpers â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    def _abstain(
        self,
        *,
        session_id: str,
        query_hash: str,
        risk_tier: str,
        reason: str,
        audit: dict,
        verification: VerificationReport | None = None,
        trust_scores: list[float] | None = None,
        chunk_ids: list[str] | None = None,
        security_context: SecurityContext | None = None,
    ) -> RAGResponse:
        """Return a structured abstention response."""
        threshold = EvidenceEligibilityGate.TIER_THRESHOLDS.get(risk_tier, 0.45)
        answer = ABSTENTION_TEMPLATE.format(
            risk_tier=risk_tier,
            threshold=threshold,
            reason=reason,
        )
        return RAGResponse(
            session_id=session_id,
            query_hash=query_hash,
            risk_tier=risk_tier,
            status=PipelineStatus.abstained,
            answer=answer,
            confidence=0.0,
            trust_scores=trust_scores or [],
            retrieved_chunk_ids=chunk_ids or [],
            gate_decision="abstain",
            verification_report=verification,
            audit_log=audit,
            security_events=security_context.cumulative_decisions if security_context else []
        )

    @staticmethod
    def _extract_drugs_simple(query: str) -> list[str]:
        """
        Fallback drug extractor: match known pharmacological suffixes.
        Used when no DrugNormalizerProtocol is injected.
        """
        pattern = re.compile(
            r"\b[A-Za-z]{3,}(?:mab|nib|olol|pril|sartan|statin|mycin|cillin|"
            r"cycline|azole|warfarin|metformin|aspirin|insulin|heparin)\b",
            re.IGNORECASE,
        )
        return list({m.lower() for m in pattern.findall(query)})

