"""
Phase 12 — Adaptive Trust-Aware Medical RAG Orchestrator.

Wires all previous phases into the complete end-to-end pipeline:

  Step 1  Input Sanitization & Prompt Injection Defense
  Step 2  Drug Entity Normalization (RxCUI resolution)
  Step 3  Query Risk Classification (R0–R3)
  Step 4  Hybrid Retrieval (BM25 + Vector + Graph + RRF)
  Step 5  Adaptive Trust Scoring per retrieved chunk
  Step 6  [PRE-GEN] Evidence Eligibility Gate
            FAIL -> Structured Abstention (no LLM call)
  Step 7  Grounded LLM Generation (pluggable backend)
  Step 8  [POST-GEN] Answer Safety Gate (claim verification)
            ABSTAIN -> Structured Abstention
            QUALIFY  -> Qualified answer released
            RELEASE  -> Full answer released
  Step 9  Audit Logging (structured, PHI-free)

All components are injected via protocol interfaces so the
orchestrator is fully unit-testable without live services.

Non-clinical disclaimer:
  Every response includes a mandatory research-output disclaimer.
  This system is NOT an FDA-approved clinical decision tool.
"""

from __future__ import annotations

import hashlib
import re
import uuid
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum
from typing import Protocol, runtime_checkable

from adaptive_trust_medical_rag.ingestion.evidence_ingestion import (
    inspect_for_poisoning,
)
from adaptive_trust_medical_rag.retrieval.hybrid_retrieval import (
    Candidate,
    DrugRelationship,
    EmbeddingModel,
    HybridRetrievalEngine,
    ScoredCandidate,
)
from adaptive_trust_medical_rag.security.sanitizer import sanitize_query
from adaptive_trust_medical_rag.trust_scoring.trust_scorer import (
    AdaptiveTrustScorer,
    TrustFactorScores,
    classify_query_risk,
)
from adaptive_trust_medical_rag.verification.claim_verifier import (
    AnswerSafetyGate,
    EvidenceChunk,
    GateDecision,
    VerificationReport,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: Mandatory disclaimer prepended to every released answer (medical safety rule)
RESEARCH_DISCLAIMER = (
    "\n\n---\n"
    "⚠ **Research Output Only** — This response is generated by an experimental "
    "research system and is NOT clinical advice, a diagnosis, or a treatment "
    "recommendation. It has not been reviewed or approved by a licensed clinician "
    "or regulatory authority (FDA/EMA). Always consult a qualified healthcare "
    "professional before making any medical decision."
)

#: Structured abstention template (controlled abstention gate — medical safety rule)
ABSTENTION_TEMPLATE = (
    "**[SYSTEM ABSTENTION — INSUFFICIENT EVIDENCE]**\n\n"
    "This query cannot be answered with the required confidence level "
    "for risk tier {risk_tier} (threshold: {threshold:.0%}).\n\n"
    "**Reason:** {reason}\n\n"
    "Please consult authoritative clinical resources (e.g., FDA label, "
    "clinical pharmacist) for this query." + RESEARCH_DISCLAIMER
)


# ---------------------------------------------------------------------------
# Protocol interfaces (dependency injection)
# ---------------------------------------------------------------------------


@runtime_checkable
class LLMBackend(Protocol):
    """
    Protocol for pluggable LLM generation backends.
    Compatible with Google GenAI, OpenAI, and local models.
    """

    def generate(self, prompt: str) -> str:
        """Generate a response for the given grounded prompt."""
        ...


@runtime_checkable
class DrugNormalizerProtocol(Protocol):
    """Protocol for drug entity normalization backends."""

    def normalize(self, query: str) -> list[str]:
        """Return a list of normalized drug names found in the query."""
        ...


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------


class PipelineStatus(str, Enum):
    released = "released"
    qualified = "qualified"
    abstained = "abstained"
    error = "error"


@dataclass
class RAGRequest:
    """Incoming query to the RAG pipeline."""

    query: str
    session_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    risk_tier_override: str | None = None  # override auto-classification if needed
    top_k: int = 10


@dataclass
class RAGResponse:
    """Final structured response from the RAG pipeline."""

    session_id: str
    query_hash: str  # SHA-256 of sanitized query (audit log — no raw PII)
    risk_tier: str
    status: PipelineStatus
    answer: str
    confidence: float
    trust_scores: list[float]
    retrieved_chunk_ids: list[str]
    gate_decision: str
    verification_report: VerificationReport | None
    audit_log: dict
    generated_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    @property
    def is_released(self) -> bool:
        return self.status in (PipelineStatus.released, PipelineStatus.qualified)


@dataclass
class EvidenceEligibilityResult:
    """Result of the pre-generation evidence eligibility gate."""

    passed: bool
    eligible_chunks: list[ScoredCandidate]
    rejected_chunk_ids: list[str]
    reason: str | None = None


# ---------------------------------------------------------------------------
# Grounded prompt builder
# ---------------------------------------------------------------------------

_PROMPT_TEMPLATE = """\
You are a medical evidence synthesis assistant. Your task is to answer the \
clinical pharmacology query below using ONLY the retrieved evidence provided. \
Do NOT generate information not present in the evidence. \
Cite each factual claim with [Source N] where N is the evidence index.

QUERY: {query}

RISK TIER: {risk_tier} — {risk_description}

RETRIEVED EVIDENCE:
{evidence_block}

INSTRUCTIONS:
- Answer in clear, precise clinical language.
- Every factual claim MUST be cited with [Source N].
- If the evidence is insufficient to answer, state that clearly.
- Do NOT speculate beyond the retrieved evidence.
- Do NOT fabricate citations, PMIDs, or dosing data.
"""

_RISK_DESCRIPTIONS = {
    "R0": "Informational / General pharmacology",
    "R1": "Standard clinical guidance",
    "R2": "High caution — vulnerable populations / black-box warnings",
    "R3": "Critical safety / contraindications / narrow therapeutic index",
}


def build_grounded_prompt(
    query: str,
    risk_tier: str,
    candidates: list[ScoredCandidate],
) -> str:
    """Build a structured, grounded prompt from retrieved evidence candidates."""
    evidence_lines: list[str] = []
    for i, sc in enumerate(candidates, start=1):
        auth = sc.candidate.source_authority
        evidence_lines.append(
            f"[Source {i}] (authority={auth:.2f}, chunk={sc.candidate.chunk_id})\n"
            f"{sc.candidate.text.strip()}"
        )
    evidence_block = "\n\n".join(evidence_lines) if evidence_lines else "(No evidence retrieved)"
    return _PROMPT_TEMPLATE.format(
        query=query,
        risk_tier=risk_tier,
        risk_description=_RISK_DESCRIPTIONS.get(risk_tier, "Unknown"),
        evidence_block=evidence_block,
    )


# ---------------------------------------------------------------------------
# Evidence Eligibility Gate (Pre-generation)
# ---------------------------------------------------------------------------


class EvidenceEligibilityGate:
    """
    Pre-generation gate: evaluates retrieved chunks before LLM context is built.

    Rejects chunks that:
    - Have poisoning_score > 0.4
    - Have trust_score below the risk-tier threshold
    - Have source_authority below minimum viable authority (0.3)

    If too few eligible chunks remain, triggers abstention.
    """

    MIN_AUTHORITY: float = 0.3
    MIN_ELIGIBLE_CHUNKS: int = 1

    #: Trust score thresholds per risk tier (mirrors medical-safety rules)
    TIER_THRESHOLDS: dict[str, float] = {
        "R0": 0.30,
        "R1": 0.45,
        "R2": 0.60,
        "R3": 0.75,
    }

    def evaluate(
        self,
        candidates: list[ScoredCandidate],
        risk_tier: str,
        trust_scores: dict[str, float],
    ) -> EvidenceEligibilityResult:
        """
        Evaluate candidates and return eligible + rejected sets.

        Args:
            candidates:   RRF-fused candidates from hybrid retrieval.
            risk_tier:    R0–R3 risk classification.
            trust_scores: chunk_id -> trust_score mapping from adaptive trust scorer.
        """
        threshold = self.TIER_THRESHOLDS.get(risk_tier, 0.45)
        eligible: list[ScoredCandidate] = []
        rejected_ids: list[str] = []

        for sc in candidates:
            cand = sc.candidate
            trust = trust_scores.get(cand.chunk_id, 0.0)

            # Poisoning gate
            if cand.poisoning_score > 0.4:
                rejected_ids.append(cand.chunk_id)
                continue
            # Trust gate
            if trust < threshold:
                rejected_ids.append(cand.chunk_id)
                continue
            # Authority gate
            if cand.source_authority < self.MIN_AUTHORITY:
                rejected_ids.append(cand.chunk_id)
                continue

            eligible.append(sc)

        if len(eligible) < self.MIN_ELIGIBLE_CHUNKS:
            return EvidenceEligibilityResult(
                passed=False,
                eligible_chunks=[],
                rejected_chunk_ids=rejected_ids,
                reason=(
                    f"Insufficient eligible evidence: {len(eligible)} chunk(s) passed "
                    f"all gates (trust >= {threshold:.2f}, poisoning <= 0.4, "
                    f"authority >= {self.MIN_AUTHORITY}). "
                    f"{len(rejected_ids)} chunk(s) rejected."
                ),
            )

        return EvidenceEligibilityResult(
            passed=True,
            eligible_chunks=eligible,
            rejected_chunk_ids=rejected_ids,
        )


# ---------------------------------------------------------------------------
# RAG Orchestrator
# ---------------------------------------------------------------------------


class AdaptiveTrustRAGOrchestrator:
    """
    End-to-end Adaptive Trust-Aware Medical RAG Orchestrator.

    Wires together all 12 pipeline phases. All backends are injected
    via protocol interfaces for testability.

    Usage:
        orchestrator = AdaptiveTrustRAGOrchestrator(
            corpus=chunks,
            embedding_model=my_embedder,
            llm_backend=my_llm,
            drug_normalizer=my_normalizer,
        )
        response = orchestrator.query(RAGRequest(query="warfarin aspirin interaction"))
    """

    def __init__(
        self,
        corpus: list[Candidate],
        embedding_model: EmbeddingModel,
        llm_backend: LLMBackend,
        drug_normalizer: DrugNormalizerProtocol | None = None,
        drug_relationships: list[DrugRelationship] | None = None,
    ) -> None:
        self._trust_scorer = AdaptiveTrustScorer()
        self._eligibility_gate = EvidenceEligibilityGate()

        # Retrieval engine — add knowledge graph edges if provided
        self._retrieval = HybridRetrievalEngine(corpus, embedding_model)
        for rel in drug_relationships or []:
            self._retrieval.graph.add_relationship(rel)

        self._llm = llm_backend
        self._drug_normalizer = drug_normalizer

    # ── Public API ────────────────────────────────────────────────────────────

    def query(self, request: RAGRequest) -> RAGResponse:
        """
        Process a clinical query through the full 12-step pipeline.

        Returns a RAGResponse with answer, confidence, and audit log.
        All audit fields are PHI-free (query stored as hash only).
        """
        session_id = request.session_id
        audit: dict = {
            "session_id": session_id,
            "pipeline_version": "12.0",
            "steps": [],
        }

        def _log(step: str, detail: dict) -> None:
            audit["steps"].append({"step": step, "ts": datetime.now(UTC).isoformat(), **detail})

        # ── Step 1: Input sanitization & injection defense ────────────────────
        sanitized_result = sanitize_query(request.query)
        sanitized_query = sanitized_result.sanitized
        query_hash = hashlib.sha256(sanitized_query.encode()).hexdigest()
        injection_check = inspect_for_poisoning(request.query)

        _log(
            "sanitization",
            {
                "query_hash": query_hash,
                "injection_score": injection_check.score,
                "injection_findings": injection_check.findings,
            },
        )

        if injection_check.is_quarantined:
            _log("injection_gate", {"decision": "abstain", "reason": "Query flagged as injection"})
            return self._abstain(
                session_id=session_id,
                query_hash=query_hash,
                risk_tier="R3",
                reason=(
                    f"Query contains prompt-injection signals (score={injection_check.score:.2f})."
                ),
                audit=audit,
            )

        # ── Step 2: Drug entity normalization ────────────────────────────────
        query_drugs: list[str] = []
        if self._drug_normalizer:
            query_drugs = self._drug_normalizer.normalize(sanitized_query)
        else:
            # Fallback: simple pattern extraction from query
            query_drugs = self._extract_drugs_simple(sanitized_query)

        _log("drug_normalization", {"normalized_drugs": query_drugs})

        # ── Step 3: Risk classification ───────────────────────────────────────
        if request.risk_tier_override:
            risk_tier = request.risk_tier_override
        else:
            risk_tier = classify_query_risk(sanitized_query)

        _log("risk_classification", {"risk_tier": risk_tier})

        # ── Step 4: Hybrid retrieval (BM25 + Vector + Graph + RRF) ───────────
        candidates = self._retrieval.retrieve(
            query=sanitized_query,
            query_drugs=query_drugs,
            top_k=request.top_k,
        )

        _log(
            "retrieval",
            {
                "candidate_count": len(candidates),
                "chunk_ids": [sc.candidate.chunk_id for sc in candidates],
            },
        )

        # ── Step 5: Adaptive trust scoring ───────────────────────────────────
        trust_scores: dict[str, float] = {}
        for sc in candidates:
            cand = sc.candidate
            entity_match = 1.0 if any(d in cand.text.lower() for d in query_drugs) else 0.5
            factors = TrustFactorScores(
                source_authority=cand.source_authority,
                entity_match=entity_match,
                freshness=float(cand.metadata.get("freshness_score", 0.8)),
                consistency=1.0 - cand.poisoning_score,
                anti_poisoning=1.0 - cand.poisoning_score,
                anti_injection=1.0 - cand.poisoning_score,
            )
            result = self._trust_scorer.score(
                chunk_id=cand.chunk_id,
                risk_class=risk_tier,
                factors=factors,
            )
            trust_scores[cand.chunk_id] = result.trust_score

        _log(
            "trust_scoring",
            {
                "scores": {cid: round(s, 4) for cid, s in trust_scores.items()},
            },
        )

        # ── Step 6: Evidence eligibility gate (pre-generation) ───────────────
        eligibility = self._eligibility_gate.evaluate(candidates, risk_tier, trust_scores)

        _log(
            "evidence_eligibility_gate",
            {
                "passed": eligibility.passed,
                "eligible_count": len(eligibility.eligible_chunks),
                "rejected_ids": eligibility.rejected_chunk_ids,
                "reason": eligibility.reason,
            },
        )

        if not eligibility.passed:
            return self._abstain(
                session_id=session_id,
                query_hash=query_hash,
                risk_tier=risk_tier,
                reason=eligibility.reason or "Evidence eligibility gate failed.",
                audit=audit,
            )

        eligible_candidates = eligibility.eligible_chunks

        # ── Step 7: Grounded LLM generation ──────────────────────────────────
        prompt = build_grounded_prompt(sanitized_query, risk_tier, eligible_candidates)
        raw_answer = self._llm.generate(prompt)

        _log("llm_generation", {"prompt_length": len(prompt), "answer_length": len(raw_answer)})

        # ── Step 8: Answer safety gate (post-generation) ─────────────────────
        evidence_chunks = [
            EvidenceChunk(
                chunk_id=sc.candidate.chunk_id,
                text=sc.candidate.text,
                source_authority=sc.candidate.source_authority,
                citation_index=i,
            )
            for i, sc in enumerate(eligible_candidates, start=1)
        ]

        safety_gate = AnswerSafetyGate(risk_tier=risk_tier)
        verification = safety_gate.verify(raw_answer, evidence_chunks)

        _log(
            "answer_safety_gate",
            {
                "decision": verification.decision.value,
                "confidence": verification.confidence,
                "grounding_ratio": verification.grounding_ratio,
                "contradiction_score": verification.contradiction_score,
                "explanation": verification.explanation,
            },
        )

        # ── Step 9: Final answer formatting ──────────────────────────────────

        if verification.decision == GateDecision.abstain:
            return self._abstain(
                session_id=session_id,
                query_hash=query_hash,
                risk_tier=risk_tier,
                reason=verification.explanation,
                audit=audit,
                verification=verification,
                trust_scores=list(trust_scores.values()),
                chunk_ids=[sc.candidate.chunk_id for sc in eligible_candidates],
            )

        final_answer = (
            verification.qualified_answer
            if verification.decision == GateDecision.qualify and verification.qualified_answer
            else raw_answer
        ) + RESEARCH_DISCLAIMER

        status = (
            PipelineStatus.qualified
            if verification.decision == GateDecision.qualify
            else PipelineStatus.released
        )

        return RAGResponse(
            session_id=session_id,
            query_hash=query_hash,
            risk_tier=risk_tier,
            status=status,
            answer=final_answer,
            confidence=verification.confidence,
            trust_scores=list(trust_scores.values()),
            retrieved_chunk_ids=[sc.candidate.chunk_id for sc in eligible_candidates],
            gate_decision=verification.decision.value,
            verification_report=verification,
            audit_log=audit,
        )

    # ── Internal helpers ──────────────────────────────────────────────────────

    def _abstain(
        self,
        *,
        session_id: str,
        query_hash: str,
        risk_tier: str,
        reason: str,
        audit: dict,
        verification: VerificationReport | None = None,
        trust_scores: list[float] | None = None,
        chunk_ids: list[str] | None = None,
    ) -> RAGResponse:
        """Return a structured abstention response."""
        threshold = EvidenceEligibilityGate.TIER_THRESHOLDS.get(risk_tier, 0.45)
        answer = ABSTENTION_TEMPLATE.format(
            risk_tier=risk_tier,
            threshold=threshold,
            reason=reason,
        )
        return RAGResponse(
            session_id=session_id,
            query_hash=query_hash,
            risk_tier=risk_tier,
            status=PipelineStatus.abstained,
            answer=answer,
            confidence=0.0,
            trust_scores=trust_scores or [],
            retrieved_chunk_ids=chunk_ids or [],
            gate_decision="abstain",
            verification_report=verification,
            audit_log=audit,
        )

    @staticmethod
    def _extract_drugs_simple(query: str) -> list[str]:
        """
        Fallback drug extractor: match known pharmacological suffixes.
        Used when no DrugNormalizerProtocol is injected.
        """
        pattern = re.compile(
            r"\b[A-Za-z]{3,}(?:mab|nib|olol|pril|sartan|statin|mycin|cillin|"
            r"cycline|azole|warfarin|metformin|aspirin|insulin|heparin)\b",
            re.IGNORECASE,
        )
        return list({m.lower() for m in pattern.findall(query)})
