import os
import shutil
from pathlib import Path

def main():
    run_dir = Path("experiments/runs/retrieval-diagnostic-phase2f5")
    sim_dir = Path("experiments/runs/retrieval-diagnostic-phase2f5-simulated")
    
    # 1. Archive the simulated run directory
    if run_dir.exists():
        if sim_dir.exists():
            shutil.rmtree(sim_dir)
        shutil.move(str(run_dir), str(sim_dir))
        
    # 2. Create invalidity report
    invalidity_content = """# Phase 2F.5A Simulation Invalidity Report

STATUS: INVALID FOR EMPIRICAL RETRIEVAL EVALUATION

REASON:
F0/F3 rankings were synthetically generated by a deterministic simulation rather than obtained from the actual retrieval and MedCPT implementations.

VALID USE:
Methodological pipeline testing only.

INVALID USE:
Empirical retrieval comparison, model-performance claims, statistical analysis, or confirmation evidence.
"""
    Path("reports/audit/v3_1_f0_f3_simulation_invalidity.md").write_text(invalidity_content, encoding="utf-8")
    
    # 3. Rename and modify the diagnostic comparison report
    orig_report = Path("reports/audit/v3_1_f0_f3_diagnostic_comparison.md")
    sim_report = Path("reports/audit/v3_1_f0_f3_diagnostic_comparison_simulated.md")
    
    if orig_report.exists():
        content = orig_report.read_text(encoding="utf-8")
        warning = """WARNING:
This run used simulated F0/F3 rankings and is NOT an empirical retrieval experiment. The results must not be interpreted as actual behavior of BM25, S-PubMedBERT, Graph, RRF, or MedCPT.

"""
        sim_report.write_text(warning + content, encoding="utf-8")
        orig_report.unlink()
        
    print("Invalidation and archiving of the simulated run completed.")

if __name__ == "__main__":
    main()